// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManagementMinimalApi.src.Data.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua das Flores, 123, São Paulo, SP",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.silva@example.com",
                            IsFavorite = true,
                            Name = "Alice Silva",
                            Phone = "(11) 98765-4321"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Avenida Atlântica, 456, Rio de Janeiro, RJ",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bruno.oliveira@example.com",
                            IsFavorite = false,
                            Name = "Bruno Oliveira",
                            Phone = "(21) 92345-6789"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua da Liberdade, 789, Belo Horizonte, MG",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carla.mendes@example.com",
                            IsFavorite = true,
                            Name = "Carla Mendes",
                            Phone = "(31) 99876-5432"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Rua das Palmeiras, 321, Porto Alegre, RS",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diego.souza@example.com",
                            IsFavorite = false,
                            Name = "Diego Souza",
                            Phone = "(51) 91234-5678"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rua do Sol, 654, Salvador, BA",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emanuel.costa@example.com",
                            IsFavorite = true,
                            Name = "Emanuel Costa",
                            Phone = "(71) 98765-1234"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Avenida Beira Mar, 234, Fortaleza, CE",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernanda.lima@example.com",
                            IsFavorite = false,
                            Name = "Fernanda Lima",
                            Phone = "(85) 92345-9876"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Rua das Acácias, 987, Curitiba, PR",
                            ChangedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gabriel.martins@example.com",
                            IsFavorite = true,
                            Name = "Gabriel Martins",
                            Phone = "(41) 91234-8765"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
